#!/bin/bash

format-to-time() {
  minutes=$(printf "%02d" $1)
  seconds=$(printf "%02d" $2)
  echo "$minutes:$seconds"
}

start-timer() {
  start = $SECONDS
  while [ $((SECONDS - start / 60)) -ne $1 ]; do
    xsetroot -name $(format-to-time $((SECONDS - start / 60)))
    sleep 1s
  done
}

start-pomodoro() {
  if [[ $@ == *"--long"* ]]; then start-timer 45; else start-timer 25; fi
  if [[ $@ == *"--long"* ]]; then start-timer 10; else start-timer 5; fi
}

"$@"
