#!/bin/bash

pomodoro_timer=30

if [[ $1 = "start" ]]; then
  current_title="$(xprop -root -notype -f WM_NAME '8u' | sed -n -r 's/WM_NAME = \"(.*)\"/\1/p')"
  while $pomodoro_timer = 0
    xsetroot -name ""
    sleep 1m &
fi

if [[ $long -eq -1 ]]; then
  echo works
  pomodoro_timer=45
fi
