#!/bin/bash

format-to-time() {
  minutes=$(printf "%02d" $1)
  seconds=$(printf "%02d" $2)
  echo "$minutes:$seconds"
}

start-timer() {
  minutes=$1
  seconds=$2
  while [[ $minutes -ne 0 || $seconds -ne 0 ]]; do
    xsetroot -name $(format-to-time $minutes $seconds)
    if [[ $seconds -eq 0 ]]; then
      ((minutes--))
      seconds=60
    fi
    ((seconds--))
    sleep 1s
  done
}

start() {
  start-timer 25 0
  if [[ $@ == *"--long"* ]]; then start-timer 15 0 else; start-timer 5 0; fi
}

"$@"
